sul-dlss/was-registrar-app

README.md
docker-compose.yml

Updates README. Tweak to docker-compose.

---

Dockerfile
README.md

Tweaks necessary to get docker env working.

---

Gemfile
Gemfile.lock
app/controllers/collections_controller.rb
app/views/collections/show.json.jbuilder
config/routes.rb
spec/factories/collections.rb
spec/rails_helper.rb
spec/requests/collection_information_spec.rb

Add API for getting collection configuration

---

Gemfile
Gemfile.lock

Adds honeybadger and capistrano for deployment related tasks.
Adds okcomputer for monitoring
Adds whenever for scheduling
Fixes #49

Add the deployment and related gems

---

.gitignore

This will be loaded from shared_configs

Remove production.yml from repo

---

app/controllers/collections_controller.rb
app/views/collections/_form.html.erb
spec/features/create_collection_spec.rb

Add Active checkbox to the form

---

.circleci/config.yml

We can just copy the files instead

Don't abuse caching without a proper key

---

README.md
app/controllers/collections_controller.rb
app/models/collection.rb
spec/factories/collections.rb
spec/requests/update_collection.rb

Add an API for setting the last crawl month

---

app/models/fetch_month.rb
db/migrate/20190820222542_create_fetch_months.rb
db/schema.rb
spec/factories/fetch_months.rb
spec/models/fetch_month_spec.rb

Generate the FetchMonth model

---

Gemfile
Gemfile.lock
config/environments/production.rb
config/routes.rb
docker-compose.yml

Add sidekiq

---

app/controllers/collections_controller.rb
app/models/collection.rb
app/views/collections/_form.html.erb
db/migrate/20190821155116_add_fetch_start_month_to_collection.rb
db/schema.rb
spec/factories/collections.rb
spec/features/create_collection_spec.rb
spec/models/collection_spec.rb
spec/views/collections/index.html.erb_spec.rb

Add fetch_start_month to Collections

---

app/controllers/collections_controller.rb
app/javascript/packs/application.js
app/javascript/src/application.scss
app/views/collections/_form.html.erb
package.json
spec/features/create_collection_spec.rb
yarn.lock

Improved date picker.

---

app/controllers/collections_controller.rb
app/models/collection.rb
app/views/collections/_form.html.erb
db/migrate/20190820154627_add_provider_and_account_to_collection.rb
db/schema.rb
spec/factories/collections.rb
spec/features/create_collection_spec.rb
spec/models/collection_spec.rb

Adds support for WASAPI provider and account

---

app/controllers/collections_controller.rb
app/models/collection.rb
app/views/collections/index.html.erb

Active is true by default. Validates that active is true or false. Renamed active on collection list page.
closes #69

Changes to active.

---

app/models/collection.rb
app/views/collections/_fetch_month.html.erb
app/views/collections/edit.html.erb

Display the FetchMonths on the Collection edit page

---

Gemfile
Gemfile.lock
app/jobs/fetch_job.rb
app/models/fetch_month.rb
config/settings.properties
config/settings.yml
config/settings/development.yml
config/settings/test.yml
spec/factories/fetch_months.rb
spec/jobs/fetch_job_spec.rb
spec/models/fetch_month_spec.rb

Create fetch job

---

app/controllers/collections_controller.rb
app/jobs/fetch_job.rb
app/models/fetch_month.rb
config/settings/development.yml
config/settings/test.yml
spec/features/create_collection_spec.rb
spec/jobs/fetch_job_spec.rb
spec/models/fetch_month_spec.rb

Removed account id from wasapi config.

---

app/jobs/fetch_job.rb
app/models/collection.rb
db/migrate/20190813151415_add_unique_key_druid.rb
db/migrate/20190820222542_create_fetch_months.rb
db/schema.rb
spec/jobs/fetch_job_spec.rb

Removes use of druid as primary key of collections.

---

.circleci/config.yml
.gitignore
Gemfile
Gemfile.lock
README.md
spec/rails_helper.rb

code coverage hooked up with code climate

---

app/views/collections/_fetch_month.html.erb
app/views/collections/edit.html.erb
spec/models/fetch_month_spec.rb

Adds crawl_item_druid to Month's status field

---

app/views/collections/edit.html.erb

Changed sort order of fetch months.

---

app/jobs/fetch_job.rb
spec/jobs/fetch_job_spec.rb

Catch errors that occur during fetch job and update FetchMonth status.

---

Gemfile
Gemfile.lock
app/components/fetch_month_component.html.erb
app/components/fetch_month_component.rb
app/components/months_component.html.erb
app/components/months_component.rb
app/views/collections/_fetch_month.html.erb
app/views/collections/edit.html.erb
config/application.rb
config/settings.yml
spec/components/fetch_month_component_spec.rb

Link to argo when crawl_item_druid is present

---

Gemfile
Gemfile.lock

Remove ruby version from Gemfile.

---

app/views/collections/_form.html.erb
app/views/collections/edit.html.erb
spec/features/create_collection_spec.rb

Added back/cancel links to edit and cancel to new collections pages.

---

app/views/collections/index.html.erb

Add provider and account to collection list page.

---

app/views/collections/index.html.erb

Adds link to Sidekiq Dashboard from Collections View

---

app/models/collection.rb
db/migrate/20190906133334_add_unique_to_collections.rb
db/schema.rb
spec/factories/collections.rb
spec/jobs/fetch_job_spec.rb
spec/models/collection_spec.rb
spec/models/fetch_month_spec.rb

Added unique index on wasapi fields for collection.

---

config/initializers/okcomputer.rb

Added additional okcomputer checks.

---

app/javascript/packs/application.js
app/javascript/src/application.scss
app/views/collections/index.html.erb
package.json
yarn.lock

Add sort and filter to collection table

---

app/views/collections/index.html.erb

That I accidentally deleted in https://github.com/sul-dlss/was-registrar-app/commit/69812b4366c174e6a61146c384a234a2e3e892b7#diff-4b055df146b82a3c8d553a83b44e01ee

Restore cols to collection list.

---

.gitignore
README.md
docker-compose.yml

closes #204
To be consistent with other SDR projects.
No.
No.

Switch to docker volumes.

---

Gemfile
Gemfile.lock
app/jobs/fetch_job.rb
spec/factories/collections.rb
spec/jobs/fetch_job_spec.rb

To upgrade to dor-services-client 5.
No.
Tested in stage.

Register with cocina model

---

.circleci/config.yml
Dockerfile

Update to ruby 2.7.1

---

yarn.lock

Github notified about security risk.

Update jquery for security vulnerability

---

app/views/collections/_form.html.erb

Help remind user that this is supposed to be a collection druid.
NA
NA

Change label to collection druid.

---

app/controllers/collections_controller.rb

Remove usage of obsolete method 'update_attributes'

---

.circleci/config.yml
.rubocop.yml
Dockerfile
Gemfile
Gemfile.lock

Test on ruby 3.0

---

.circleci/config.yml

Switched to sul-dlss/ruby-rails orb for circleci config.

---

app/jobs/fetch_job.rb
spec/jobs/fetch_job_spec.rb

Register objects with citation-only access

---

app/jobs/fetch_job.rb
spec/jobs/fetch_job_spec.rb

refs https://github.com/sul-dlss/cocina-models/issues/343
Less hardcoding.

Removes hardcoded vocab terms.

---

Capfile
Gemfile
Gemfile.lock

Needed with migration to Ubuntu

Adding capistrano/rvm

---

.rubocop.yml
bin/webpack
bin/webpack-dev-server
spec/models/collection_spec.rb

Enabled new rubocops.

---

README.md

Add test:prepare to README.

---

Gemfile
Gemfile.lock
app/javascript/application.js
package.json
yarn.lock

Add turbo and stimulus

---

config/initializers/simple_form.rb
config/initializers/simple_form_bootstrap.rb

Updated simple form initializers.

---

.circleci/config.yml

To be consistent with dev instructions.

Switch circle to use test:prepare

---

app/controllers/collections_controller.rb
app/views/collections/_form.html.erb

This is the right way to handle validation failure.

Return unprocessable entity when validation fails.

---

spec/jobs/register_job_spec.rb

refs #472
Follow-up from code review.

Adds test for error in Register Job.

---

.rubocop.yml

Enable new cops.

---

spec/factories/registration_jobs.rb

refs #468
Carryover from code review.

Correctly use sequence in registration job factory.

---

.rubocop.yml

Enable new rubocops.

---

config/schedule.rb
config/settings.yml

Fixes https://github.com/sul-dlss/was-registrar-app/issues/534
See also https://github.com/sul-dlss/shared_configs/pull/1903

add HB checkins for cron

---

.github/pull_request_template.md

consistent and semantically correct headings

Normalize headings in pull_request_template.md

---

README.md
config/settings.yml
db/seeds.rb

Fixes: https://github.com/sul-dlss/argo/issues/4045

Document qa/stage reset

---

Gemfile
Gemfile.lock
spec/services/audit/sdr_warc_lister_spec.rb

Update cocina models and DSC

---

Gemfile
Gemfile.lock

Gemfile: alphabetized and config gem unpinned

---

.circleci/config.yml

Latest version of the ruby orb is 4.2.1

Update ruby orb to latest version

---

.rubocop.yml
Dockerfile
README.md

Bump Ruby to 3.3.1

---

.circleci/config.yml
.erb-lint.yml
.eslintrc.js
Gemfile
Gemfile.lock
Rakefile
app/components/actions_component.html.erb
app/components/fetch_months_component.html.erb
app/components/registration_jobs_component.html.erb
app/javascript/controllers/application.js
app/javascript/controllers/index.js
app/views/collections/_form.html.erb
app/views/collections/index.html.erb
app/views/home/index.html.erb
app/views/layouts/application.html.erb
app/views/layouts/mailer.html.erb
app/views/registration_jobs/_form.html.erb
app/views/registration_jobs/index.html.erb
package.json
yarn.lock

Avoid bikeshedding and strive for consistency
- **Set up ERB linting in CI**
- **Apply ERB lint fixes**
- **Set up JS linting in CI**
- **Apply JS lint fixes**
CI

Set up linting of ERBs and JavaScript

---

README.md
compose.yaml

https://docs.docker.com/compose/compose-application-model/#the-compose-file

Rename docker-compose.yml to compose.yaml

---

.circleci/config.yml
.rubocop.yml
Dockerfile
README.md

To keep things up to date.
CI and integration tests in stage + qa

Update to Ruby 3.4.1
