sul-dlss/was-registrar-app

- Gemfile
- Gemfile.lock
also, chromedriver-helper has been deprecated.
> Remove unnecessary test dependencies

- Gemfile
- Gemfile.lock
Now that Sidekiq 6 has been released, which removes the ability to daemonize
sidekiq, we must pin sidekiq until we are daemonizing sidekiq via systemd (vs.
the sidekiq executable in the bundle). Note the tracking issue in
capistrano-sidekiq: https://github.com/seuros/capistrano-sidekiq/issues/224
> Pin sidekiq to version 5.x

- Gemfile.lock
- app/jobs/fetch_job.rb
- config/settings.yml
This is no longer required, and in fact can break the client if the header value (from shared_configs) is unset. This is what broke the workflow service connection to dor-services-app.
> Remove token_header keyword arg when configuring dor-services-client

- spec/rails_helper.rb
Telling simplecov it's a Rails app means it will give more accurate stats on code coverage.
N/A
> tell coveralls it's a rails app

- .circleci/config.yml
- .rspec
- spec/spec_helper.rb
In slack, jcoyne said:
> @Naomi Dushay something is really wrong with the coverage of was-registrar-app.
> It thinks FetchJob has 0% coverage, but it has a test: https://github.com/sul-dlss/was-registrar-app/blob/master/spec/jobs/fetch_job_spec.rb
Based on what I read, I believe this will work to get appropriate coverage showing in code climate.
n/a
> Fix coverage

- .circleci/config.yml
The coverage stats reported to CodeClimate were off;  I think it was only getting 1 out of 3 of the parallel builds.  This is a small app with a small number of fast running tests so getting rid of parallel builds in order to get accurate coverage data seems like a win.
n/a
> we don't need to run tests in parallel in code climate

- app/assets/config/manifest.js
App assets could not be built (e.g. as part of cap deploy) because we don't have an `app/assets/stylesheets` directory, because we don't have any stylesheets.
```
[ndushay@m3dl-sm-03-mbph-2 was-registrar-app (master)]$ bx rake assets:precompile
yarn install v1.17.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.47s.
rake aborted!
Sprockets::ArgumentError: link_directory argument must be a directory
/Users/ndushay/sul-dlss-github/was-registrar-app/app/assets/config/manifest.js:3
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```
n/a
> missing stylesheets directory cannot precompile

- app/jobs/fetch_job.rb
- spec/jobs/fetch_job_spec.rb
not submitting a version is deprecated
n/a
> Submit a version when creating a workflow

- Gemfile
- Gemfile.lock
actionview-component was renamed to view_component
no
no
> Update to view_component 2.1

- config/initializers/okcomputer.rb
Adds Sidekiq latency check to Okcomputer
n/a
> Adds Sidekiq latency check

- Gemfile
- Gemfile.lock
Do this because when dlss-capistrano 4.0 comes out, codebases that use both dlss-capistrano and capistrano-sidekiq without pinning the former will find it clobbering the sidekiq tasks from the latter, and that will cause confusion and woe.
> Pin dlss-capistrano to 3.x

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/prod.rb
- config/deploy/stage.rb
Consistency with the rest of our portfolio; keeping pace with dependency updates; ability to upgrade rack to pick up security patches.
Deployed to stage and prod to ensure # of workers stayed at 1, with just the 1 thread.
None needed, AFAIK.
> Upgrade to sidekiq 6 and dlss-capistrano 3.6 (to manage sidekiq)

- README.md
- config/deploy.rb
Updates references to the new default branch: `main`
> Update references from master to main

- app/jobs/fetch_job.rb
> Make download value explicit instead of relying on default.

- config/application.rb
doing so raises a deprecation warning
> There is no need to require view_components explicity

- config/deploy.rb
We don't need the overrides; the defaults work. I will test this in all three envs once merged.
> Stop overriding passenger defaults

- Gemfile
- Gemfile.lock
Partly because I forgot to pull main ...
- no longer need to restrict simplecov gem.
> simplecov no longer needs version restriction

- config/sidekiq.yml
> Add default queue to sidekiq configuration.

- config/environments/production.rb
Jobs were getting added to the default queue, which has no workers.
> Set correct queue name prefix.

- config/application.rb
This prevents deprecation errors like:
```
DEPRECATION WARNING: Non-URL-safe CSRF tokens are deprecated. Use 6.1 defaults or above. (called from <top (required)> at /Users/jcoyne85/workspace/sul-dlss/was-registrar-app/spec/rails_helper.rb:14)
DEPRECATION WARNING: Using legacy connection handling is deprecated. Please set
to  in your application.
```
> Use Rails 6.1 defaults

- .dockerignore
- .gitignore
The web container won't start up without `tmp/pids`:
```
➜  was-registrar-app git:(main) docker compose up web
[+] Running 3/0
⠿ Container was-registrar-app-redis-1  Running                                                                 0.0s
⠿ Container was-registrar-app-db-1     Running                                                                 0.0s
⠿ Container was-registrar-app-web-1    Created                                                                 0.0s
Attaching to was-registrar-app-web-1
was-registrar-app-web-1  | Puma starting in single mode...
was-registrar-app-web-1  | * Puma version: 5.6.4 (ruby 3.0.4-p208) ("Birdie's Version")
was-registrar-app-web-1  | *  Min threads: 5
was-registrar-app-web-1  | *  Max threads: 5
was-registrar-app-web-1  | *  Environment: …
```
> Keep the tmp/pids directory in Git

- docker-compose.yml
Not use deprecated redis version in dev
running specs, bringing up containers and confirming no errors
> Unpin redis docker image

- Dockerfile
- docker-compose.yml
Makes app easier to use for development, using a volume with the code. Switches to using alpine version of base image and reduces image size from 1.46GB to 1.06GB. Removes specifying older bundler version. 
Running locally
> Uses alpine base image and updates docker config

- Gemfile.lock
- config/deploy.rb
To successfully register HB deployments. This is a known situation on some of our Ubuntu boxes.
Before this change, I deployed to QA and the honeybadger:deploy step failed. After, it passed.
> Invoke honeybadger deployment cap task under RVM

- README.md
Need wasapi-downloader version 1.1.1 to get bug fix.
> Update README wasapi-downloader version to download

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
We are testing handling this via puppet instead, by ensuring a default system bashrc is executed, which will take care of RVM bootstrapping.
CI + QA
> Remove capistrano-rvm and other bits added to help deploy to ubuntu boxes

- Gemfile
- Gemfile.lock
- app/models/collection.rb
- app/validators/collection_druid_validator.rb
- app/views/collections/_form.html.erb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- spec/features/create_collection_spec.rb
- spec/models/collection_spec.rb
closes #309
More resilient to user error.
Unit, qa
> Strips whitespace from collection form and validates collection druid.

- Gemfile
- Gemfile.lock
- README.md
- app/jobs/fetch_job.rb
- app/services/audit/sdr_warc_lister.rb
- app/services/audit/warc_auditer.rb
- app/services/audit/wasapi_warc_lister.rb
- app/validators/collection_druid_validator.rb
- config/initializers/dor_services_client.rb
- lib/tasks/audit.rake
- spec/rails_helper.rb
- spec/services/audit/sdr_warc_lister_spec.rb
- spec/services/audit/warc_auditer_spec.rb
- spec/services/audit/wasapi_warc_lister_spec.rb
closes #428
Complete data.
Stage, unit
> Adds rake task for auditing WARCs.

- config/schedule.rb
refs #482
To avoid having to reindex.
> Temporarily disabling fetching collections

- Gemfile
- Gemfile.lock
- app/models/registration_job.rb
- app/validators/unique_source_id_validator.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- spec/models/registration_job_spec.rb
closes #471
Prevent user error.
Unit, QA
> Validate that source id is unique for one-time registration.

- Dockerfile
- Procfile.dev
- README.md
- bin/dev
- docker-compose.yml
- docker/invoke.sh
Closes #470 
This copies much of the work done in Argo to make docker-compose utilize bin/dev for local execution.
> Update docker compose to use bin/dev for web service

- .rubocop.yml
- README.md
- app/services/audit/warc_auditer.rb
- app/services/audit/warc_remediator.rb
- app/services/audit/wasapi_warc_lister.rb
- lib/tasks/audit.rake
- spec/services/audit/warc_auditer_spec.rb
- spec/services/audit/warc_remediator_spec.rb
- spec/services/audit/wasapi_warc_lister_spec.rb
refs #486
Support remediation for missing WARCs.
Unit, QA
> Adds rake task for remediation.

- app/models/collection.rb
- app/views/collections/_form.html.erb
- db/migrate/20220720185025_set_embargo.rb
- db/schema.rb
- spec/models/collection_spec.rb
- spec/services/fetch_job_creator_spec.rb
closes #500
This avoids a race condition with Archive-It making WARC files available.
Unit, local
> Sets a minimum embargo of 1 month.

- spec/models/collection_spec.rb
- spec/models/registration_job_spec.rb
I find the tests easier to read when using predicate matchers for simple tests like these.
CI
> Switch to RSpec predicate matchers to test validity

- README.md
- app/services/audit/warc_auditer.rb
- app/services/audit/warc_remediator.rb
- lib/tasks/audit.rake
- spec/services/audit/warc_auditer_spec.rb
- spec/services/audit/warc_remediator_spec.rb
closes #504
Not all collections that require auditing/remediation are in WRA.
QA
> Adds rake task for auditing and remediating non-WRA collections.

- .rubocop.yml
noticed this when i was running tests locally while working on weekly dependency updates.
ran rspec locally, CI
n/a
no
> catch up on missing rubocop rules

- app/views/collections/_form.html.erb
Currently the earliest start year is set to `Time.zone.today.year - 15` which is no longer earlier enough, we have acquired some content from as early as 1990.
> Set the earliest start year to 1990
